### ISSUE TITLE
老哥，我也想做一个插画分享网站，能发下数据库文件让我参考下吗？

### ISSUE THREAD

**Issue by Chrixe** [CorvusCoraxZero/GraduationProject_Scintillate#1]
RT，谢谢老哥

**Comment by CorvusCoraxZero** [comment]
em.........&nbsp; 身边只带了笔记本&nbsp; 这个工程在宿舍台式上&nbsp; 你要是等得及的话&nbsp; 我星期一发你吧&nbsp;&nbsp;
当时为了考研复试&nbsp; 就只做了个框架出来好多功能都没有来得及做....&nbsp;&nbsp;┑(￣Д ￣)┍
后来换方向了&nbsp; 就彻底搁下了.......


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CorvusCoraxZero/GraduationProject_Scintillate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 晚上8:23
收件人:&nbsp;"CorvusCoraxZero/GraduationProject_Scintillate"<GraduationProject_Scintillate@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[CorvusCoraxZero/GraduationProject_Scintillate] 老哥，我也想做一个插画分享网站，能发下数据库文件让我参考下吗？ (#1)





 
RT，谢谢老哥
